<?php return [
  'key' => '',
  'title' => '',
  'fields' => [],
  'location' => null,
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => [
    0 => 'permalink',
    1 => 'the_content',
    2 => 'excerpt',
    3 => 'custom_fields',
    4 => 'discussion',
    5 => 'comments',
    6 => 'revisions',
    7 => 'slug',
    8 => 'author',
//  9 => 'format',
//  10 => 'page_attributes',
    11 => 'featured_image',
    12 => 'categories',
    13 => 'tags',
    14 => 'send-trackbacks',
  ],
  'active' => 1,
  'description' => '',
];
