<?php return [
  'key' => '',
  'label' => '',
  'name' => '',
  'type' => 'post_object',
  'instructions' => '',
  'required' => 0,
  'conditional_logic' => 0,
  'wrapper' => [
    'width' => '',
    'class' => '',
    'id' => '',
  ],
  'post_type' => [],
  'taxonomy' => [],
  'allow_null' => 0,
  'multiple' => 0,
  'return_format' => 'object',
  'ui' => 1,
];
