<?php return array(
  'key' => '',
  'label' => '',
  'name' => '',
  'type' => 'text',
  'instructions' => '',
  'required' => 0,
  'conditional_logic' => 0,
  'wrapper' => array(
    'width' => '',
    'class' => '',
    'id' => '',
  ),
  'default_value' => '',
  'placeholder' => '',
  'prepend' => '',
  'append' => '',
  'maxlength' => '',
  'readonly' => 0,
  'disabled' => 0,
);
