<?php return [
  'key' => '',
  'label' => '',
  'name' => '',
  'type' => 'textarea',
  'instructions' => '',
  'required' => 0,
  'conditional_logic' => 0,
  'wrapper' => [
    'width' => '',
    'class' => '',
    'id' => '',
  ],
  'default_value' => '',
  'placeholder' => '',
  'maxlength' => '',
  'rows' => '',
  'new_lines' => 'wpautop',
  'readonly' => 0,
  'disabled' => 0,
];
